const mightyWinterPlayers = [
    { name: "Touré", ovr: 111, position: "CDM", shardCost: 1000, imageUrl: "https://i.ibb.co/YBzsxh1b/Tour-111.png" },
    { name: "Bergkamp", ovr: 111, position: "CAM", shardCost: 800, imageUrl: "https://i.ibb.co/Kxsf9CVY/Bergkamp-111.png" },
    { name: "Schweinsteiger", ovr: 110, position: "CM", shardCost: 800, imageUrl: "https://i.ibb.co/LX8Fn5Q3/Schweinsteiger-110.png" },
    { name: "Lizarazu", ovr: 110, position: "LB", shardCost: 650, imageUrl: "https://i.ibb.co/9mNY11xP/Lizarazu-110.png" },
    { name: "Reus", ovr: 109, position: "CAM", shardCost: 300, imageUrl: "https://i.ibb.co/99j93zQY/Reus-109.png" },
    { name: "Trippier", ovr: 109, position: "RB", shardCost: 300, imageUrl: "https://i.ibb.co/RG8qjFGk/Trippier-109.png" },
    { name: "Santa Cruz", ovr: 108, position: "ST", shardCost: 200, imageUrl: "https://i.ibb.co/ZCjGv1S/Santa-Cruz-108.png" },
    { name: "Ginola", ovr: 111, position: "ST", shardCost: 1500, imageUrl: "https://i.ibb.co/LX12fJRg/Ginola-111.png" },
    { name: "Nedved", ovr: 111, position: "LM", shardCost: 1000, imageUrl: "https://i.ibb.co/tT7g5XR2/Nedv-d-111.png" },
    { name: "Oblak", ovr: 110, position: "GK", shardCost: 800, imageUrl: "https://i.ibb.co/sds6bP91/Oblak-110.png" },
    { name: "Cambiaso", ovr: 110, position: "CDM", shardCost: 500, imageUrl: "https://i.ibb.co/21QBwrYP/Cambiasso-110.png" },
    { name: "Beasley", ovr: 109, position: "LM", shardCost: 450, imageUrl: "https://i.ibb.co/7x1HjBMn/Beasley-109.png" },
    { name: "Aubameyang", ovr: 109, position: "ST", shardCost: 300, imageUrl: "https://i.ibb.co/1YtZGXZ7/Aubameyang-109.png" },
    { name: "Zaha", ovr: 108, position: "LW", shardCost: 200, imageUrl: "https://i.ibb.co/TBk2Bnk5/Zaha-108.png" },
    { name: "Charlton", ovr: 111, position: "CAM", shardCost: 1250, imageUrl: "https://i.ibb.co/tMYKkL1b/Charlton-111.png" },
    { name: "Carlos Alberto", ovr: 111, position: "RB", shardCost: 1500, imageUrl: "https://i.ibb.co/HTN6sLsF/Carlos-Alberto-111.png" },
    { name: "King", ovr: 110, position: "CB", shardCost: 650, imageUrl: "https://i.ibb.co/MxyjNdP7/King-110.png" },
    { name: "Hagi", ovr: 110, position: "RM", shardCost: 800, imageUrl: "https://i.ibb.co/S73LwJLb/Hagi-110.png" },
    { name: "Guti", ovr: 109, position: "CM", shardCost: 300, imageUrl: "https://i.ibb.co/RTrcPTtd/Guti-109.png" },
    { name: "Szczesny", ovr: 109, position: "GK", shardCost: 450, imageUrl: "https://i.ibb.co/HLjGWTHY/Szcz-sny-109.png" },
    { name: "Abedi Pelé", ovr: 108, position: "CAM", shardCost: 200, imageUrl: "https://i.ibb.co/J02tzhL/Abedi-Pele-108.png" },
    { name: "Best", ovr: 111, position: "LW", shardCost: 1250, imageUrl: "https://i.ibb.co/jPGFnCRR/Best-111.png" },
    { name: "Drogba", ovr: 111, position: "ST", shardCost: 1250, imageUrl: "https://i.ibb.co/ks20vdjH/Drogba-111.png" },
    { name: "Keane", ovr: 110, position: "CDM", shardCost: 500, imageUrl: "https://i.ibb.co/wN4txFZt/Keane-110.png" },
    { name: "Lampard", ovr: 110, position: "CM", shardCost: 650, imageUrl: "https://i.ibb.co/schrWXT/Lampard-110.png" },
    { name: "Burn", ovr: 109, position: "CB", shardCost: 300, imageUrl: "https://i.ibb.co/Q7TNpbLM/Burn-109.png" },
    { name: "Pedro", ovr: 109, position: "RW", shardCost: 300, imageUrl: "https://i.ibb.co/wVjCwwz/Pedro-109.png" },
    { name: "Guerreiro", ovr: 108, position: "LB", shardCost: 300, imageUrl: "https://i.ibb.co/HLKfQD1N/Guerreiro-108.png" },
    { name: "Blanc", ovr: 111, position: "CB", shardCost: 1250, imageUrl: "https://i.ibb.co/21kkxNb6/Blanc-111.png" },
    { name: "Yashin", ovr: 111, position: "GK", shardCost: 1250, imageUrl: "https://i.ibb.co/CK8jpzrs/Yashin-111.png" },
    { name: "Griezmann", ovr: 110, position: "CAM", shardCost: 650, imageUrl: "https://i.ibb.co/hRTb0MQ8/Griezmann-110.png" },
    { name: "Carvajal", ovr: 110, position: "RB", shardCost: 800, imageUrl: "https://i.ibb.co/Gr53t9n/Carvajal-110.png" },
    { name: "Mané", ovr: 109, position: "LW", shardCost: 450, imageUrl: "https://i.ibb.co/5xYztP1j/Man-109.png" },
    { name: "Giroud", ovr: 109, position: "ST", shardCost: 300, imageUrl: "https://i.ibb.co/MyBWNXry/Giroud-109.png" },
    { name: "Coates", ovr: 108, position: "CB", shardCost: 200, imageUrl: "https://i.ibb.co/LDv1YTjp/Coates-108.png" },
    { name: "Palmer", ovr: 111, position: "CAM", shardCost: 1000, imageUrl: "https://i.ibb.co/Nn1fkpQ9/Palmer-111.png" },
    { name: "Garrincha", ovr: 111, position: "RW", shardCost: 1000, imageUrl: "https://i.ibb.co/Xkvkp201/Garrincha-111.png" },
    { name: "Mascherano", ovr: 110, position: "CDM", shardCost: 500, imageUrl: "https://i.ibb.co/HL1DHHV7/Mascherano-110.png" },
    { name: "Völler", ovr: 110, position: "ST", shardCost: 650, imageUrl: "https://i.ibb.co/YTwXvdFH/V-ller-110.png" },
    { name: "Sergio Busquets", ovr: 109, position: "CDM", shardCost: 300, imageUrl: "https://i.ibb.co/svgmBpRp/Sergio-Busquets-109.png" },
    { name: "Nacho Fernández", ovr: 109, position: "CB", shardCost: 300, imageUrl: "https://i.ibb.co/yBYshqDG/Nacho-Fern-ndez-109.png" },
    { name: "Henderson", ovr: 108, position: "CM", shardCost: 200, imageUrl: "https://i.ibb.co/wFFV9P6t/Henderson-108.png" },
    { name: "Vidal", ovr: 108, position: "CDM", shardCost: 200, imageUrl: "https://i.ibb.co/SCbJkwf/Vidal-108.png" },
    { name: "Santi Cazorla", ovr: 108, position: "CM", shardCost: 200, imageUrl: "https://i.ibb.co/SkPXSC1/Santi-Cazorla-108.png" },
    { name: "Meunier", ovr: 108, position: "RB", shardCost: 200, imageUrl: "https://i.ibb.co/99pn5NMr/Meunier-108.png" },
    { name: "Zardes", ovr: 108, position: "ST", shardCost: 300, imageUrl: "https://i.ibb.co/Y4mQccHt/Zardes-108.png" },
    { name: "Joao Moutinho", ovr: 108, position: "CM", shardCost: 200, imageUrl: "https://i.ibb.co/v6YR5bMm/Jo-o-Moutinho-108.png" },
    { name: "Sissoko", ovr: 108, position: "CDM", shardCost: 200, imageUrl: "https://i.ibb.co/XfL2nNcT/Sissoko-108.png" }
];

const afterDaybreakPlayers = [
    { name: "Bellingham", ovr: 111, position: "CM", shardCost: 1500, imageUrl: "https://i.ibb.co/XkWsQfbh/Bellingham-111.png" },
    { name: "Bergvall", ovr: 108, position: "CM", shardCost: 200, imageUrl: "https://i.ibb.co/LXrsXKhw/Bergvall-108.png" },
    { name: "DELAP", ovr: 108, position: "ST", shardCost: 200, imageUrl: "https://i.ibb.co/nNHcrw99/Delap-108.png" },
    { name: "ECHEVERRI", ovr: 108, position: "CAM", shardCost: 200, imageUrl: "https://i.ibb.co/PzDTBfpG/Echeverri-108.png" },
    { name: "FELLAINI", ovr: 110, position: "CM", shardCost: 800, imageUrl: "https://i.ibb.co/23FYfZKZ/Fellaini-110.png" },
    { name: "FERDINAND", ovr: 111, position: "CB", shardCost: 1500, imageUrl: "https://i.ibb.co/rGKHT53b/Ferdinand-111.png" },
    { name: "HAALAND", ovr: 111, position: "ST", shardCost: 1250, imageUrl: "https://i.ibb.co/xpsd7DD/Haaland-111.png" },
    { name: "HUIJSEN", ovr: 110, position: "CB", shardCost: 800, imageUrl: "https://i.ibb.co/gFJzX4fX/Huijsen-110.png" },
    { name: "IBRAHIMOVIC", ovr: 111, position: "ST", shardCost: 1500, imageUrl: "https://i.ibb.co/Cpsbc5vs/Ibrahimovi-111.png" },
    { name: "KOULIERAKIS", ovr: 108, position: "CB", shardCost: 200, imageUrl: "https://i.ibb.co/Q31rtsgR/Koulierakis-108.png" },
    { name: "MARC CASADÓ", ovr: 109, position: "CDM", shardCost: 300, imageUrl: "https://i.ibb.co/G3pFVyT1/Marc-Casad-109.png" },
    { name: "MUSIALA", ovr: 111, position: "CAM", shardCost: 1000, imageUrl: "https://i.ibb.co/d0qJhTxH/Musiala-111.png" },
    { name: "NUSA", ovr: 109, position: "LM", shardCost: 300, imageUrl: "https://i.ibb.co/RkkQRLfT/Nusa-109.png" },
    { name: "OWEN", ovr: 110, position: "ST", shardCost: 650, imageUrl: "https://i.ibb.co/JRpsqgVV/Owen-110.png" },
    { name: "SAKA", ovr: 110, position: "RW", shardCost: 800, imageUrl: "https://i.ibb.co/BVxWPd2G/Saka-110.png" },
    { name: "UDOGIE", ovr: 109, position: "LB", shardCost: 450, imageUrl: "https://i.ibb.co/tT0XXVs6/Udogie-109.png" },
    { name: "WOLTEMADE", ovr: 109, position: "ST", shardCost: 300, imageUrl: "https://i.ibb.co/9kB8s7CY/Woltemade-109.png" }
];
